import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
const inter = Inter({ subsets: ["latin"] });
import ContextProvider from "./context/context-wrapper";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-full h-full flex bg-primary">
          <ContextProvider>
            <Sidebar />
            {children}
          </ContextProvider>
        </main>
      </body>
    </html>
  );
}
